### ISSUE TITLE
Case insensitive routes

### ISSUE THREAD

**Issue by epignosisx** [reach/router#127]
Looks like routes are case sensitive. So one of these two will not be a match "/Dashboard" and "/dashboard". Take a look at: https://codesandbox.io/s/z2qw8zykmp

Not sure if this was a design decision or should this be considered a bug?

**Comment by clechner77** [comment]
Yes, this bit me today too.  Basename is case sensitive and it gave me a bit of a headache today.

**Comment by chiester** [comment]
+1

**Comment by r1cs1** [comment]
Is there any update on this?

**Comment by clechner77** [comment]
This is one of those things that I really hope gets looked at.  At the very least, perhaps it could be an option only.

**Comment by mupkoo** [comment]
To me it is clear that `/Dashboard` and `/dashboard` can be two different pages, and even Google will treat them as such. And I think that it is expected behaviour and one that can found in other tool like Rails and Ember.js

**Comment by millette** [comment]
They can be different, but arean't always, example: https://github.com/reAch/Router

**Comment by ryanflorence** [comment]
Hmm, everything after the TLD has historically been case sensitive since it's originally based on file systems.

I can see the desire to be case insensitive, and maybe that's the right thing today in a modern client-side router, but I'm going to close this issue to avoid introducing something that might make the merging of React Router and @reach/router harder.

We'll consider it over there in the future :)

For context: https://reacttraining.com/blog/reach-react-router-future/

**Comment by akshayrathodar** [comment]
Yes, this needs to be resolve. Any Update ?
