### ISSUE TITLE
Website does not sync with source code

### ISSUE THREAD

**Issue by ng-hai** [reach/router#190]
## Think you found a bug?
Yes

## Have a question?
I got a problem when implementing `navigate` API according to the website docs, so I found that the `navigate` doc was not in sync with sources code. It led to misunderstanding and wasting time.
![image](https://user-images.githubusercontent.com/19520278/47711124-09dcaf00-dc67-11e8-90a0-986603a20b96.png)

**Comment by antoinegrant** [comment]
This as been fixed in this commit: https://github.com/reach/router/commit/e8325ae7a2d7be0a4e1de266ee15929f85fc2d94#diff-880640c648fc6a2a7ffd8e71cd14c97eR101

The issue, now at least, is that the website docs does not reflect the latest release https://github.com/reach/router/releases/tag/v1.2.0

![image](https://user-images.githubusercontent.com/810246/54483779-f4d87500-482f-11e9-8eb5-f21a0577c546.png)
