### ISSUE TITLE
Router does not work on Chrome v 43.0.2357.81

### ISSUE THREAD

**Issue by magnusarinell** [reach/router#230]
Steps to reproduce:

Visit https://reactjs.org/docs/hello-world.html with Chrome  v 43.0.2357.81.

**Comment by timdorr** [comment]
That is a very very very old, unsupported version of Chrome. It _shouldn't_ work.

**Comment by magnusarinell** [comment]
Ok. I get the same error when running react-snapshot which uses jsdom. uri.split fails since uri is undefined in utils.js:34.

**Comment by jaredLunde** [comment]
@timdorr It's actually important to support a minimum version of Chrome 41 because otherwise Google's web renderer won't render your app when it is crawled. See: https://developers.google.com/search/docs/guides/rendering

It's more important for non-SSR apps but still important generally. Not saying Reach Router itself should transpile to this target, but definitely not something to write off/teach as *it shouldn't work*. It *definitely should*.

@magnusarinell are you transpiling your app with something like babel? You should transpile the entirety of your build including node_modules. `create-react-app` will do this for you in its latest version.
