### ISSUE TITLE
Export LocationContext for useContext usage

### ISSUE THREAD

**Issue by universse** [reach/router#259]
Hi. Is it possible to export LocationContext for easy access to location with useContext hook?

**Comment by Hitscotty** [comment]
Yea, I could really use this as well. Was trying to find ways to plug in Location props without wrapping Location everywhere.

**Comment by mtliendo** [comment]
@ryanflorence has made a few references [on Twitter](https://twitter.com/ryanflorence/status/1089332213080965120?s=20) about what the upcoming hook based API may yield.  It would make use cases like this hopefully a lot easier.  

Gonna go ahead and close this since new API will greatly help in providing `location`. Feel free to checkout the [roadmap](https://reacttraining.com/blog/reach-react-router-future/) if you haven't already.
