### ISSUE TITLE
Can I prefetch / preload data before the route is processed?

### ISSUE THREAD

**Issue by shukriadams** [reach/router#271]
Does this router support loading of data before a route is handled? I would like to do something like
    
    async function fetchMyData(props){
        props.viewData = await ajax(`/server/${props.id}`);
    } 
   
    <Router>
        <MyComponent path="/view/:id" preload={fetchMyData}>
    </Router>

    class MyComponent extends React.Component {
        render(){
            return(
                <Fragment>
                    {this.props.viewData}
                </Fragment>
            );
        }
    }
    
The route for MyComponent calls fetchMyData before proceeding to mount MyComponent, at which point the data is already bound to props. This spares my component the mess of having to maintain a "busy" and a "done" view state, and lets me cleanly separate data and view logic. I've been trying for hours to get this to work in react-router-dom, but it doesn't look like they support it.

**Comment by jvitela** [comment]
It doesn't support loading data before the URL navigation happens because it relies on the Browser to resolve the navigation path.

However I made a demo that showcases data prefetching using a method "getInitialProps" like Next.js does plus lazy loading and animating transitions between routes. You can find it here: 

https://github.com/jvitela/reach-router-lazy-transitions

**Comment by shukriadams** [comment]
@jvitela thanks for the reply, closing this ticket then. I'll give your solution a try too.
