### ISSUE TITLE
Dependency warning

### ISSUE THREAD

**Issue by septvean** [reach/router#272]
Hi, when I use yarn to install package, I get this warning:

```
warning @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
```

How to fix it?

**Comment by danielkov** [comment]
As you can see, this is caused by a dependency of a package that polyfills v16+ `Context` API. You could wait until they merge jamiebuilds/create-react-context/pull/22 and then submit a PR here to update version of `create-react-context` or wait for @ryanflorence to join efforts with [ReactTraining/react-router](https://github.com/ReactTraining/react-router) team again and release v5, which will be the successor of this package. [Read more about that here.](https://reacttraining.com/blog/reach-react-router-future/)

**Comment by timbomckay** [comment]
`create-react-context` Has released 4 updates removing `fbjs` which has the `core-js@1.2.7` dependency. Can this package get updated to resolve this warning?

**Comment by mtliendo** [comment]
Closing as stale. 

As @danielkov mentioned, PR's are welcome, though due to it not causing any issues with the router, it wouldn't be as high a priority as some of  the other tasks we have at the moment. If bugs are spotted with the current version of corejs however, feel free to open a new issue. In the meantime, feel free to disregard the warning.
