### ISSUE TITLE
Link with query param is not marked as active

### ISSUE THREAD

**Issue by just-boris** [reach/router#280]
## Think you found a bug?

Codesandbox example: https://hhylx.csb.dev/
Source: https://codesandbox.io/s/reach-router-starter-v1-hhylx

The link "Home" is expected to become bold when it is active, but it does not, because is has a query-parameter in `to` prop, but the library considers only `location.pathname`.

The expected behavior, that the "Home" link is getting highlighted as well as "Dashboard".

**Comment by theneva** [comment]
I have the exact same problem, and this behaviour seems like a bug to me. At least in my mental model of the URL, query parameters should not be used to determine which route to render.

Since this repo is [not under active development](https://reacttraining.com/blog/reach-react-router-future/) (and my project is stuck on version 1.2.0 due to an issue with 1.2.1 that I can't remember right now), I used `patch-package` to patch `@reach/router`.

My `./patches/@reach+router+1.2.0.patch` looks like this:

```diff
diff --git a/node_modules/@reach/router/es/index.js b/node_modules/@reach/router/es/index.js
index 27eb5f6..763fd4e 100644
--- a/node_modules/@reach/router/es/index.js
+++ b/node_modules/@reach/router/es/index.js
@@ -460,8 +460,9 @@ var Link = forwardRef(function (_ref4, ref) {
               anchorProps = _objectWithoutProperties(props, ["to", "state", "replace", "getProps"]);
 
           var href = resolve(to, baseuri);
-          var isCurrent = location.pathname === href;
-          var isPartiallyCurrent = startsWith(location.pathname, href);
+          var hrefWithoutQuery = href.split('?')[0];
+          var isCurrent = location.pathname === hrefWithoutQuery;
+          var isPartiallyCurrent = startsWith(location.pathname, hrefWithoutQuery);
 
           return React.createElement("a", _extends({
             ref: ref || innerRef,
```

This behaviour at least makes sense for our project, and I believe it also makes sense for the general case. It would be great if this issue were considered for the new API in react-router.

**Comment by ryanflorence** [comment]
It's not super convenient, but `location` gets passed to `getProps`, so you can do whatever matching you need to there on `location.pathname` and `location.search`.

We're going to be making query params 1st class in React Router v6.
