### ISSUE TITLE
PropTypes error on 'undefined' url-param

### ISSUE THREAD

**Issue by oren-l** [reach/router#326]
See issue here: https://codesandbox.io/s/reach-router-starter-v1-m1065

I Just added PropTypes to the [url-params example](https://reach.tech/router/example/url-params)

**Comment by blainekasten** [comment]
@oren-l this actually seems like a bug with React if anything. We don't do anything special here. It seems like maybe prop-types is firing at some point during a cloneElement maybe? 

I'm going to close this because I don't see a way for the router to address this. Feel free to keep the conversation going here however! If you find this is an issue with the router and can contribute a bug fix, please ping back!

**Comment by CharlyPoppins** [comment]
Hello, strange behaviour... 

@oren-l maybe you should ask there : https://github.com/facebook/prop-types/issues

This trick avoid the warning :

````
<Router>
//    <MerchantPage path="/merchant/:merchantId" />
      <MerchantRoute path="/merchant/:merchantId" />
</Router>
````

````
import MerchantPage from 'components/MerchantPage'

const MerchantRoute = ({ merchantId }) => {
  if (!merchantId) {
    return null
  }

  return <MerchantPage merchantId={merchantId} />
}

MerchantRoute.propTypes = {
  merchantId: PropTypes.string,
}

MerchantRoute.defaultProps = {
  merchantId: null,
}

````
