### ISSUE TITLE
Trouble implementing a modal

### ISSUE THREAD

**Issue by reflog** [reach/router#42]
Hi!
First of all - amazing project. Love the new API!
A small question, I'm having trouble implementing a modal, i.e. a component that has a sub-path and appears with the previous path "behind it".

Here's an example: https://codesandbox.io/s/nr50qor62j

The problem is: even though a modal component has a `path` prop (prop is "edit", so the modal should appear at "/clients/edit") that doesn't match the url (url is "/clients") the modal is still rendered.

What am I missing?

Thanks in advance!

**Comment by taurose** [comment]
NavBar is missing in your sandbox.

Judging by https://reach.tech/router/example/embedded-routers I think you're missing two things:

* you need to wrap every `Route component` (with a path prop) inside a `<Router>`. Child route components are only automatically picked up when you render in the same component as direct children
* you need to specify the path of `ClientList` as `/clients/*`, otherwise it won't match "/clients/edit"

**Comment by reflog** [comment]
I've simplified the code to make it easier to read.
I've also tried to add your suggestion of nested Router - it didn't help, now the route is not recognized at all. I'm probably missing something obvious here :(

**Comment by taurose** [comment]
It works for me if you navigate directly..
And for the button click, it seems you have to put the `onAction` callback inside actions object `primaryAction={{ content: "Add", onAction: () => navigate("/clients/crap") }}`

**Comment by reflog** [comment]
You are absolutely right. It does work. Silly me :)
Thank you!
