### ISSUE TITLE
Global hooks?

### ISSUE THREAD

**Issue by liamwang** [reach/router#45]
Is there a global hook or single router hook in reach-router? or some good custom impementation? this feature is really quite useful.

I also use Vue, it's offical implementation is like below: 
```javascript
router.beforeEach((to, from, next) => {...})
```
I can do some intercept things, like api request and ssr pre-fetch data etc.

**Comment by timdorr** [comment]
[One of the trade-offs](https://reach.tech/router/credits) is "no history blocking", so there wouldn't be a middleware-style `next` approach to this. And given that, I'd just respond to changes from `<Location>` or listen to a `createHistory()` instance.

**Comment by ryanflorence** [comment]
When Suspense lands, you won't need to pre-fetch data server side since we'll have streaming and components can be asynchronous, waiting for data as they render.

https://www.youtube.com/watch?v=z-6JC0_cOns

Not sure what you'd "intercept" but to perform side-effects on location changes (like analytics? should be an example!) use a component:

```jsx
import Component from '@reactions/component'
const TrackPageViews = () => (
  <Location>
    {({ location }) => (
      <Component
        didMount={() => track(location.pathname)}
        didUpdate={() => track(location.pathname)}
      />
    )}
  </Location>
)
```

Or data loading you do in `componentDidMount` of your route components.
