### ISSUE TITLE
Feature discussion: Configure focus, aria-live and setting document title via props.

### ISSUE THREAD

**Issue by AlmeroSteyn** [reach/router#55]
After the thread on focus and `aria-live` / setting doc title in [this tweet](https://twitter.com/ryanflorence/status/1004771480431759361) I was thinking whether props could be added to toggle this. 

**Scenario 1**: Setting focus after navigation is awesome but what if I am loading multiple viewports for the same route?

I quickly put this together this morning to test my theory:
```
<aside>
  <Router>
    <Complementary1 path="page1" />
    <Complementary2 path="page2/*" />
  </Router>
</aside>
<main>
  <Router>
    <Page1 path="page1" />
    <Page2 path="page2/*" />
  </Router>
</main>
``` 

It appears that, by default, focus is set on the last component rendered at a route. So in this case the focus always bypasses the `<aside>`, meaning this change remains 'silent' to AT. 

I had a look at the [doc on multiple routers](https://reach.tech/router/example/multiple-routers) to see if I was doing something stupid but it happens there too.

**Scenario2**: Adding live announcing and changing the document title on route change. 

This was pretty much discussed in the tweet above and would think that main navigations should be announced to AT in the same way normal page navigation would be.

But smaller changes should perhaps not.

**Suggestion**: What if there were props to configure this. Something like:

**focusPriority**: A prop that, if set, provides a way to prioritize where focus will go after navigation. In the code example above, I would probably rather have the `<aside>` get focus in some cases. 

**announce**: A prop that, if set,  tells the router to announce to AT with `aria-live` and maybe even with the text to announce or an ID of the text container.

**doctitle**: A prop that, if set, tells the router to set the doc title with the given text.

I have no idea if this fits in the planned architecture but this was milling in my head all night and thought I'd put it down. 

CC @ryanflorence @Heydon

**Comment by ryanflorence** [comment]
### `focusPriority`

We already have this as `primary={true}`, which gets focus (and is the default). `primary={false}` will not get focus.

If people need more focus management than "focus this router when pages change" then they can use `primary={false}` everywhere and manage focus themselves.

I think trying to get any fancier than what we have now will turn this lib into a general focus management lib--which is something I've tried and failed at a few times and don't have the energy for now :P

### Announcing and Titles

The tricky stuff here is that usually you want to use data that the component fetches for the title, not just boring "Event" but "Event - Slurpees w/ the kids".

When Suspense lands, this might be easier to do since componentDidMount of the tree waits for data. So I'm kind of waiting to explore that more.

So I don't think there's anything to do on this issue right now. When suspense lands and we get a little experience with it, let's reopen. Feel free to add any other thoughts here in the mean time :)

**Comment by AlmeroSteyn** [comment]
Thanks @ryanflorence!

I agree with you on the focus management. I totally did not know that the `primary={true}` part existed. Missed that is the spec. Sorry :-)

As for announcing we would be able to achieve that level of announcing using similar techniques to what I used in my [react-aria-live package](https://www.npmjs.com/package/react-aria-live).

But I suppose then I can just keep using this package to announce both the router changes as well as any other app changes. 

So yeah I agree :-)

Really awesome project, by the way. Thanks for caring!
