### ISSUE TITLE
Router doesn't catch navigate on "first render"

### ISSUE THREAD

**Issue by ricardobrandao** [reach/router#91]
Hi,

I believe I've found the following issue: When a user navigates to a given path which immediately redirects to another one, the Router does not render properly. However, adding a ```setTimeout(() => ..., 0)``` around the navigate function will do the trick. Please note that this behaviour doesn't happen when the user uses the router links to navigate.

An example is available on the following [codesandbox](https://codesandbox.io/s/242q8r4q1y). Refreshing the browser on https://242q8r4q1y.codesandbox.io/working (the component with the setTimeout) will properly render the Redirected component. However, refreshing on https://242q8r4q1y.codesandbox.io/not-working will not render the component.

**Comment by ryanflorence** [comment]
Server rendering won't be able to catch that redirect, you should use a `<Redirect />` component in your route config instead.

This happens because we haven't subscribed to the location until the component higher up the tree has mounted (`LocationProvider`). We should probably add a warning if we detect an attempt to redirect before the parent `LocationProvider` has subscribed and suggest using `Redirect` instead.

**Comment by ckreiling** [comment]
To folks who have seen this issue, be sure to pass the `noThrow` Boolean prop into the `Redirect` component (`<Redirect to="/some/other/url" noThrow />`) if you're doing this client-side. The [docs for `Redirect`](https://reach.tech/router/api/Redirect) describe the prop in a bit more detail.

**Comment by akoolenbourke** [comment]
Thanks. I also figured this one out after much head scratching
