### ISSUE TITLE
Redirect doesn't work with relative links

### ISSUE THREAD

**Issue by hardfist** [reach/router#94]
I try use Redirect in a nested Route components, but it seems that the "from" supports relative link but the "to" props doesn't supports relative links, which is odd。You can see it in the  [demo](https://codesandbox.io/s/4ljz2o78qw)

**Comment by ryanflorence** [comment]
Oops, yep:

https://github.com/reach/router/blob/054187e17795c5c2df289109456ce42c48f49343/src/index.js#L421 and https://github.com/reach/router/blob/054187e17795c5c2df289109456ce42c48f49343/src/index.js#L429

Need to use `resolve()`

**Comment by S-iscoming** [comment]
@ryanflorence  Hey there, I encountered the same issue recently. I'm wondering are there any plan to fix this, because the pr is still open.  Thanks :)

**Comment by davidleger95** [comment]
Is this still working properly? I seem to be experiencing the same issue. Here's an example:

```jsx
<ProfilePage path="/profile">
    <Redirect from="/" to="about" /> {/* redirects to `localhost.com/about` instead of `localhost.com/profile/about`  */}
    <AboutPage default path="/about" />
    <SettingsPage path="/settings" />
</ProfilePage>
```

Maybe I'm using this incorrectly though?

I want to do this because I'm also using `isPartiallyCurrent` to style active tabs with multiple nav levels. So I need the link to be `<Link to="/profile">` but redirect to `/profile/about` so that `isPartiallyCurrent` will be true for the `profile` nav link and the `about` nav link.

An alternative could be to just use the about page as the default and not add the `/about` path but then the about nav link gets highlighted for all sub nav paths.

Any insight would be appreciated!
